# Generated by Django 6.0.1 on 2026-03-13 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('celular', models.CharField(max_length=20)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gym')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
                ('clase', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('cuota_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gym')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.membership')),
            ],
            options={
                'unique_together': {('gym', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miembros.alumnos')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miembros.clases')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gym')),
            ],
            options={
                'unique_together': {('clase', 'alumno')},
            },
        ),
        migrations.CreateModel(
            name='Avisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('vencimiento', 'Próximo a vencer'), ('impago', 'Cuota impaga')], max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha_generado', models.DateTimeField(auto_now_add=True)),
                ('visto_por_profesor', models.BooleanField(default=False)),
                ('fecha_visto', models.DateTimeField(blank=True, null=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gym')),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miembros.inscripciones')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('Inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miembros.inscripciones')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gym')),
            ],
            options={
                'unique_together': {('Inscripcion', 'mes', 'anio')},
            },
        ),
    ]
