# Generated by Django 6.0.1 on 2026-04-06 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagos',
            old_name='Inscripcion',
            new_name='inscripcion',
        ),
        migrations.AlterUniqueTogether(
            name='pagos',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pagos',
            name='fecha_fin',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='pagos',
            name='fecha_inicio',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='pagos',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fecha_pago',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='pagos',
            name='updated_at',
        ),
    ]
