# Generated by Django 6.0.1 on 2026-01-19 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clases',
            name='clase',
            field=models.CharField(default='clase', max_length=30),
        ),
    ]
