# Generated by Django 6.0.1 on 2026-03-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_remove_clases_dia_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripciones',
            name='fecha_vencimiento',
            field=models.DateField(db_index=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='avisos',
            unique_together={('inscripcion', 'tipo')},
        ),
    ]
