# Generated by Django 6.0.1 on 2026-01-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_clases_clase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clases',
            name='alumno',
        ),
    ]
