# Generated by Django 6.0.1 on 2026-01-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0003_remove_clases_alumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripciones',
            name='cuota_mensual',
        ),
        migrations.AddField(
            model_name='clases',
            name='cuota_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
