# Generated by Django 6.0.1 on 2026-02-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0004_remove_inscripciones_cuota_mensual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clases',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
