# Generated by Django 6.0.1 on 2026-02-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0005_clases_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripciones',
            old_name='Alumnos',
            new_name='alumno',
        ),
        migrations.AlterField(
            model_name='clases',
            name='clase',
            field=models.CharField(max_length=30),
        ),
    ]
