# Generated by Django 6.0.1 on 2026-02-08 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0006_rename_alumnos_inscripciones_alumno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripciones',
            old_name='fecha_incripcion',
            new_name='fecha_inscripcion',
        ),
    ]
