# Generated by Django 6.0.1 on 2026-03-20 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_usuario',
            name='gym_activo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.gym'),
        ),
        migrations.AlterField(
            model_name='gym',
            name='direccion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gym',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='gym',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='rol',
            field=models.CharField(choices=[('owner', 'Dueño'), ('Admin_Gym', 'Administrador'), ('profesor', 'Profesor')], max_length=20),
        ),
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('rol', models.CharField(choices=[('Admin_Gym', 'Administrador'), ('profesor', 'Profesor')], max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('usos_maximos', models.IntegerField(default=1)),
                ('usos_actuales', models.IntegerField(default=0)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gym')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
