# Generated by Django 6.0.1 on 2026-04-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_gym_direccion_alter_gym_nombre_alter_gym_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitacion',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('profesor', 'Profesor')], max_length=20),
        ),
    ]
